# Generated by Django 5.1.3 on 2024-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
    ]
