# Generated by Django 5.1.3 on 2024-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('summery', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='detail',
            field=models.CharField(max_length=5000),
        ),
    ]
