# Generated by Django 5.1.3 on 2025-01-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_next_alter_feature_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='detail',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='int',
        ),
        migrations.AddField(
            model_name='feature',
            name='phone',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
