# Generated by Django 5.1.3 on 2025-02-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_my_table_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='my_order',
        ),
    ]
