# Generated by Django 5.1.3 on 2025-02-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_order_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_order',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='my_order',
            table='my_order',
        ),
    ]
