# Generated by Django 5.1.3 on 2025-02-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_my_order_customer_id_alter_my_order_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_table',
            new_name='my_customer',
        ),
        migrations.AlterModelTable(
            name='my_customer',
            table='my_customer',
        ),
    ]
