# Generated by Django 5.1.3 on 2025-02-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_my_table_my_customer_alter_my_customer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_order',
        ),
    ]
