# Generated by Django 5.1.3 on 2025-02-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_my_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_customer',
        ),
    ]
