# Generated by Django 5.1.3 on 2025-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_my_customer_my_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='my_customer',
            table='my_Customer',
        ),
        migrations.AlterModelTable(
            name='my_order',
            table='my_Order',
        ),
    ]
